### PR TITLE
Js delete

### PR DESCRIPTION
**Pull request by JohnSheets**
Description:

Added Delete function for categories. [Trello Ticket #11](https://trello.com/c/j8mOAyHn/11-11-delete-a-category)

Testing Instructions:

git add and git commit whatever you're working on on your branch
git checkout main
git fetch --a
git checkout js-Delete
If you don't see the most recent version of my files, git pull origin js-Delete
If you haven't created the Tabloid MVC database, please do so.
Use this to fill out tables and columns: [SQL data](https://github.com/NewForce-Cohort-6/tabloidmvc-the-bit-o-honeys/blob/main/SQL/01_TabloidMVC_Create_DB.sql)
Use this to seed the database: [SQL Seed Data](https://github.com/NewForce-Cohort-6/tabloidmvc-the-tootsie-rolls/blob/main/SQL/02_TabloidMVC_Seed_Data.sql)

create a new SQL query by going to Object Explorer -> TabloidMVC -> new query 
Paste INSERT INTO Category (Name) VALUES ('TV Shows'); to create a new category 
paste SELECT * FROM Category and execute to see a list of all the categories
Click the execute with debugger solid green button to launch the app
In browser, please go to Login on the nav bar and log in with this email: admin@example.com
This should redirect you back to the home page.
Navigate to the categories page and delete the one titled "TV Shows"
It should ask if you are sure you want to delete, choose to delete the category and you should be taken back to the list
Now go back to the SQL query and run SELECT * FROM Category again 
You should see that the category is no longer there because it has been deleted from the database as well

Checklist:

 My code follows the style guidelines of this project
 I have performed a self-review of my code
 I have commented my code, particularly in hard-to-understand areas
 My changes generate no new warnings or errors
 I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by AustinCDavis** [comment]
Tested and functioning as described

**Comment by KierstenWhite** [comment]
Works as described!

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
- We want to protect our data so please include an insert SQL statement with some dummy data that the user can delete so that they don't delete something from the current database that could potentially break our app.

**Review by sarahebrooks12 — APPROVED** [review]
Looks good 👼

**Pull request merged**
