### PR TITLE
KW - Updated Ticket #3

### PR DESCRIPTION
**Pull request by KierstenWhite**
**Description**

Relooked over tickets to make sure all details were actually done, and they were not. So, this specific pull request is finishing ticket #3 so that View All Posts will be in order of the Publication Date.

**Testing Instructions**
1. git add and git commit whatever you're working on on your branch
2. git checkout main
3. git fetch --a
4. git checkout kw-EditPost
5. If you don't see the most recent version of my files, git pull origin kw-EditPost
6. To see what posts are in the database, right click to the TabloidMVC Database in the SQL Server Object Explorer, selecting "Create a New Query."
7. In the query, type "Select * from Posts". This will show you any and all posts in the database. There should be at least one post in your database (C# is the Best Language) if you have run the initial SQL Scripts.
8. Click the execute with debugger solid green button to launch the app
9. In browser, please go to Login on the nav bar and log in with this email: admin@example.com
10. This should redirect you back to the home page.
11. Click Posts in the Nav Bar to view a lists of Posts.
12. Please create at least one new post using the New Post button at the top of the page that has a publication date of 6/28/2023 or before.
13. Once you add the post, the posts on the Index page should be listed in the order of their publication dates, as long as they are in the past, and should appear because they are set to be automatically approved.

Checklist:
 [x] My code follows the style guidelines of this project
 [x] I have performed a self-review of my code
 [] I have commented my code, particularly in hard-to-understand areas
 [x] My changes generate no new warnings or errors
 [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
- Please include a select SQL statement that allows users to see exactly what should be in the database so that they can compare and contrast what is showing on the website
- Great job

**Review by sarahebrooks12 — APPROVED** [review]
Looks great 👼

**Comment by JohnSheets** [comment]
Works as it should

**Comment by AustinCDavis** [comment]
Tested and works as described

**Pull request merged**
